src/main/java/com/just/jstruct/model/Jstruct_User.java
package com.just.jstruct.model;

import com.hfg.util.StringUtil;
import com.just.jstruct.enums.UserStatus;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Entity class for: Jstruct_User
 */
// -------------------------------------------------------------------------------------
// Copyright (c) 2023 Just-Evotec Biologics, Inc.
// All rights reserved
// See the LICENSE.txt file included with this library for license terms and conditions.
// -------------------------------------------------------------------------------------
@Entity
@Table(name = "jstruct_user", schema = "public")
@NamedQueries({
    @NamedQuery(name = "Jstruct_User.findAll", 
                                            query = "SELECT u FROM Jstruct_User u"),
    
    @NamedQuery(name = "Jstruct_User.findByUserId", 
                                            query = "SELECT u FROM Jstruct_User u "
                                                  + "WHERE u.userId = :userId"),
    
    @NamedQuery(name = "Jstruct_User.findByUid", 
                                            query = "SELECT u FROM Jstruct_User u "
                                                  + "WHERE UPPER(u.uid) = :uid"),
    
    @NamedQuery(name = "Jstruct_User.findUsersByGeneralCriteria", query = "SELECT u FROM Jstruct_User u "
                                                                        + " WHERE "
                                                                        + "  (    UPPER(u.uid)      LIKE :criteria "
                                                                        + "    OR UPPER(u.name)     LIKE :criteria "
                                                                        + "  ) "
                                                                        + "  AND ( u.uid NOT LIKE '" + Jstruct_User.SYSTEM_UID + "') "
                                                                        + "  AND ( u.uid NOT LIKE '" + Jstruct_User.GUEST_UID + "') "
                                                                        + "ORDER BY u.name"),
    
    @NamedQuery(name = "Jstruct_User.findActiveRoleDevelopers", query = "SELECT u FROM Jstruct_User u "
                                                                     + " WHERE u.roleDeveloper LIKE 'Y' "
                                                                     + "   AND u.status LIKE 'ACTIVE' "),
    
    @NamedQuery(name = "Jstruct_User.findActiveRoleAdmins", query = "SELECT u FROM Jstruct_User u "
                                                                  + " WHERE u.roleAdmin LIKE 'Y' "
                                                                  + "   AND u.status LIKE 'ACTIVE' "),
    
    @NamedQuery(name = "Jstruct_User.findActiveRoleContributers", query = "SELECT u FROM Jstruct_User u "
                                                                        + " WHERE u.roleContribute LIKE 'Y' "
                                                                        + "   AND u.status LIKE 'ACTIVE' ")
})  
public class Jstruct_User implements Serializable {
    
    
    public static final String SYSTEM_UID = "JSTRUCT_SYSTEM";
    public static final String GUEST_UID = "JSTRUCT_GUEST";

    
    private static final long serialVersionUID = 1L;
    
    
    
    @Id
    @SequenceGenerator(name="jstruct_user_user_id_seq", sequenceName="jstruct_user_user_id_seq", allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="jstruct_user_user_id_seq")
    @Basic(optional = false)
    @Column(name = "user_id", updatable=false)
    private Long userId;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 1000)
    @Column(name = "uid")
    private String uid;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "name")
    private String name;
    
    // @Pattern(regexp="[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", message="Invalid email")//if the field contains email address consider using this annotation to enforce field validation
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "email")
    private String email;
    
    @Size(max = 256)
    @Column(name = "img_url")
    private String imgUrl;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 100)
    @Column(name = "status")
    private String status;
    
    
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "role_developer")
    private Character roleDeveloper;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "role_admin")
    private Character roleAdmin;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "role_contribute")
    private Character roleContribute;
    
    
    
    
    /* ------------ audit fields ------------ */
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "insert_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date insertDate;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "update_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateDate;
    
    @Column(name = "insert_user_id", insertable=false, updatable=false)
    private Long insertUserId;
    
    @Basic(optional = false)
    @NotNull
    @JoinColumn(name = "insert_user_id", referencedColumnName = "user_id")
    @ManyToOne(optional = false,fetch = FetchType.LAZY)
    private Jstruct_User insertUser;
    
    @Column(name = "update_user_id", insertable=false, updatable=false)
    private Long updateUserId;
    
    @Basic(optional = false)
    @NotNull
    @JoinColumn(name = "update_user_id", referencedColumnName = "user_id")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Jstruct_User updateUser;
    
    /* --------- end audit fields --------- */
    
    
    
    
    
    public Jstruct_User() {
    }

    
    
    
    
    public Jstruct_User(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    
    
    public UserStatus getStatus(){
        UserStatus userStatus = null;
        if (StringUtil.isSet(this.status)){
            userStatus = UserStatus.valueOf(this.status);
        }
        return userStatus;
    }
    public void setStatus(UserStatus inValue) {
        this.status = inValue != null ? inValue.name() : null;
    }
    
    //public String getStatus() { return status; }
    //public void setStatus(String status) { this.status = status; }

    
    public boolean getIsRoleDeveloper() { return roleDeveloper.equals('Y') || roleDeveloper.equals('y'); }
    public void setRoleDeveloper(boolean roleDeveloper) { this.roleDeveloper = roleDeveloper ? 'Y' : 'N' ; }
    
    public boolean getIsRoleAdmin() { return roleAdmin.equals('Y') || roleAdmin.equals('y'); }
    public void setRoleAdmin(boolean roleAdmin) { this.roleAdmin = roleAdmin ? 'Y' : 'N' ; }
    
    public boolean getIsRoleContributor() { return roleContribute.equals('Y') || roleContribute.equals('y'); }
    public void setRoleContributor(boolean roleContribute) { this.roleContribute = roleContribute ? 'Y' : 'N' ; }
    
   

    public Date getInsertDate() {return insertDate;}
    public void setInsertDate(Date insertDate) {this.insertDate = insertDate; }

    public Date getUpdateDate() {return updateDate;}
    public void setUpdateDate(Date updateDate) { this.updateDate = updateDate;}

    public long getInsertUserId() {return insertUserId;}
    public void setInsertUserId(long insertUserId) { this.insertUserId = insertUserId;}
    
    public Jstruct_User getInsertUser() {return insertUser;}
    public void setInsertUser(Jstruct_User insertUser) { this.insertUser = insertUser;}

    public long getUpdateUserId() { return updateUserId;}
    public void setUpdateUserId(long updateUserId) {this.updateUserId = updateUserId;}
    
    public Jstruct_User getUpdateUser() {return updateUser;}
    public void setUpdateUser(Jstruct_User updateUser) { this.updateUser = updateUser;}
    
    
    
    /**
     * determine if this is the 'guest' user
     * @return 
     */
    public boolean isGuest(){
        return getUid().equals(GUEST_UID);
    }
    
    
    /**
     * determine if this is the 'system' user
     * @return 
     */
    public boolean isSystem(){
        return getUid().equals(SYSTEM_UID);
    }

   
    
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (userId != null ? userId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {

src/main/java/com/just/jstruct/backing/HeaderBean.java
package com.just.jstruct.backing;

import com.just.jstruct.model.Jstruct_User;
import com.just.jstruct.pojos.AuthState;
import com.just.jstruct.pojos.SessionBean;
import com.just.jstruct.utilities.AuthUtil;
import com.just.jstruct.utilities.FacesUtil;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Backing bean for the header 
 */
// -------------------------------------------------------------------------------------
// Copyright (c) 2023 Just-Evotec Biologics, Inc.
// All rights reserved
// See the LICENSE.txt file included with this library for license terms and conditions.
// -------------------------------------------------------------------------------------
@ManagedBean(name="headerBean") 
@ViewScoped
public class HeaderBean implements Serializable {
 
    private static final long serialVersionUID = 1L;
    
    
     
     
   
    
    /* data members */
    @ManagedProperty(value="#{sessionBean}")
    private SessionBean sessionBean;
    
    private Jstruct_User currentUser;
    
    private String username;
    private String password;
    
    

    
    //constructor
    public HeaderBean() { 
    }
    
    @PostConstruct
    public void init() {
        currentUser = sessionBean.getUser();
    }


    
    
    //getters/setters
    public SessionBean getSessionBean() {return sessionBean;}
    public void setSessionBean(SessionBean sessionBean) {this.sessionBean = sessionBean;}
    
    public Jstruct_User getCurrentUser() { return currentUser; }
    public void setCurrentUser(Jstruct_User currentUser) { this.currentUser = currentUser; }
    
    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }
    
    
    
    /* actions */
    
    public void authAttempt(ActionEvent actionEvent){
        
        HttpServletRequest request = FacesUtil.getRequest();
        HttpServletResponse response = FacesUtil.getResponse();
        
        AuthUtil authUtil = new AuthUtil();
        AuthState authState = authUtil.authenticateUser(username, password, request, response);
        
        if(authState.isAuthenticated()){
            
            //authentication success - redirect to home
            FacesUtil.redirectRequest("/home.xhtml?faces-redirect=true"); //todo get login page from applicationresources.properties
            
        } else {
            
            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, authState.getAuthFailMessage(),  null);
            FacesContext.getCurrentInstance().addMessage(null, message);
            
        }
         
    }
    
    public String logout(){
        AuthUtil.logout(FacesUtil.getRequest(), FacesUtil.getResponse());
        return "/home.xhtml?faces-redirect=true";  //todo get login page from applicationresources.properties
    }
    
    
    
    
    
    
    
    
/*
    public ProcessControl getProcessControl() { return processControl; }
    public void setProcessControl(ProcessControl processControl) { this.processControl = processControl; }

    public Collection<AutoJob> getAutoJobs() { return autoJobs; }
    public void setAutoJobs(Collection<AutoJob> autoJobs) { this.autoJobs = autoJobs; }
    
    public Collection<JobHistory> getJobHistorys() { return jobHistorys; }
    public void setJobHistorys(Collection<JobHistory> jobHistorys) { this.jobHistorys = jobHistorys; }

    public int getRecentHistoryCount() { return recentHistoryCount; }
    public void setRecentHistoryCount(int recentHistoryCount) { this.recentHistoryCount = recentHistoryCount; }
    */

    

    
    
    
    
    
    
    
    
}

src/main/webapp/layout/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui">


    <script language="JavaScript" type="text/javascript">
        //mouse over
        function roll_over(img_name, img_src) {
            document[img_name].src = img_src;
        }

        //http://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript
        function copyToClipboard(inText)
        {
            var textArea = document.createElement("textarea");

            //
            // *** This styling is an extra step which is likely not required. ***
            //
            // Why is it here? To ensure:
            // 1. the element is able to have focus and selection.
            // 2. if element was to flash render it has minimal visual impact.
            // 3. less flakyness with selection and copying which **might** occur if
            //    the textarea element is not visible.
            //
            // The likelihood is the element won't even render, not even a flash,
            // so some of these are just precautions. However in IE the element
            // is visible whilst the popup box asking the user for permission for
            // the web page to copy to the clipboard.
            //

            // Place in top-left corner of screen regardless of scroll position.
            textArea.style.position = 'fixed';
            textArea.style.top = 0;
            textArea.style.left = 0;

            // Ensure it has a small width and height. Setting to 1px / 1em
            // doesn't work as this gives a negative w/h on some browsers.
            textArea.style.width = '2em';
            textArea.style.height = '2em';

            // We don't need padding, reducing the size if it does flash render.
            textArea.style.padding = 0;

            // Clean up any borders.
            textArea.style.border = 'none';
            textArea.style.outline = 'none';
            textArea.style.boxShadow = 'none';

            // Avoid flash of white box if rendered for any reason.
            textArea.style.background = 'transparent';


            textArea.value = inText;

            document.body.appendChild(textArea);

            textArea.select();

            try {
                var successful = document.execCommand('copy');
                var msg = successful ? 'successful' : 'unsuccessful';

                //Ext.toast({html: '<div style="text-align:center;">The text: <br/><br/><pre>' + inText + '</pre><br/><br/>has been copied to your clipboard.</div>', align: 't'});
                console.log('Copy to clipboard command was ' + msg + '(' + inText + ')');

            } catch (err) {
                //Ext.toast({html: '<div style="text-align:center;">Unable to copy text;<br/><br/>clipboard may not be supported by your current browser.</div>', align: 't'});
                console.log('Oops, unable to copy');
            }

            document.body.removeChild(textArea);
        }
    </script>








    <table style="width:100%; background-color: #{msg.AppInstance ne 'production' ? '#EAFF00' : ''};" cellspacing="0" >  <!-- #ffee00 -->
        <tr>

            <td class="titleCell" style="vertical-align: top;" >

                <div style="float: left;">
                    <a href="https://just-evotecbiologics.com/" target="_blank" style="text-decoration:none">
                        <p:graphicImage value="/images/just_logo_144.png" alt="Just – Evotec Biologics" title="Just – Evotec Biologics" style="margin-right:20px; height:27px; "/>
                    </a>
                </div>
                <div style="float: left; margin-top:1px">
                    <a href="/jstruct/home.xhtml" style="text-decoration:none">
                        <p:graphicImage value="/images/jstruct_logo_lg.svg" alt="JStruct home" title="JStruct home" style="margin-right:20px; height:23px; "/>
                    </a>
                </div>
                <div style="float: left; margin-left: 20px">
                    <h:outputText styleClass="devTestWarn"
                                  rendered="#{msg.AppInstance!='production'}"
                                  value=" (#{msg.AppInstance})"/>
                </div>
            </td>



            <td class="userCell">


                <!-- NOT logged in (guest) -->
                <c:if test="#{headerBean.currentUser.guest}">  <!-- alternatively we could (should?) use the 'rendered' attribute from an 'h' element instead of c:if -->

                    <h:form id="authForm">

                        <p:growl id="loginGrowl"/>
                        
                        <h:outputText value="Domain: #{msg.LDAP_CorpDomain}" style="color:#555555; margin-right: 10px;"/>
                       
                        <p:inputText id="username"
                                     placeholder="username"
                                     style="width:111px; margin-right:8px; "
                                     maxlength="99"
                                     value="#{headerBean.username}"
                                     required="true" 
                                     requiredMessage="Username is required">
                        </p:inputText>

                        <p:password id="password"
                                    placeholder="password"
                                    style="width:111px; margin-right:8px; "
                                    maxlength="99"
                                    value="#{headerBean.password}"
                                    required="true" 
                                    requiredMessage="Password is required">
                        </p:password>

                        <p:commandButton id="loginBtn"
                                         title="Login"
                                         icon="ui-icon-key"
                                         update="loginGrowl"
                                         actionListener="#{headerBean.authAttempt}">
                        </p:commandButton>


                    </h:form>

                </c:if>

                <!-- user has been authenticated -->
                <c:if test="#{!headerBean.currentUser.guest}">
                    <h:outputText value="#{headerBean.currentUser.name}" 
                                  style="font-size: 1.1em; font-weight:bold; "
                                  title="#{headerBean.currentUser.uid} (#{headerBean.currentUser.email})"/>
                    <br/>
                    <h:outputText value=" [Contributor]" rendered="#{headerBean.currentUser.isRoleContributor}"/>
                    <h:outputText value=" [Admin]" rendered="#{headerBean.currentUser.isRoleAdmin}"/>
                    <h:outputText value=" [Developer]" rendered="#{headerBean.currentUser.isRoleDeveloper}" style="color:#ff0000; "/>
                </c:if>
            </td>



            <td class="logoutCell">
                <!-- user has been authenticated -->
                <c:if test="#{!headerBean.currentUser.guest}">

                    <h:form id="logoutForm" >

                        <p:commandButton id="logoutBtn"
                                         title="Log out" 
                                         icon="ui-icon-cancel" 
                                         immediate="true" 
                                         action="#{headerBean.logout}"/>
                    </h:form>
                </c:if>
            </td>



        </tr>
    </table>
    
    
    
    
    <!-- *******************************************************************************************************
            non-displaying required text for SONAR 
            https://johndeere.justbiotherapeutics.com:9999/Sonar
    -->
    <span style="font-size: 0; color: transparent;">
        PAGE TEXT FOR SONAR
    </span>
    <!-- ******************************************************************************************************* -->




</ui:composition>

src/main/webapp/layout/menu.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui">


    <h:form id="menuForm" style="overflow:hidden; position: relative;">

        <!-- 
            http://jqueryui.com/themeroller/
            http://www.petefreitag.com/cheatsheets/jqueryui-icons/ 
        -->



        <p:menu style="width:100%; border:0px solid #ff00ff; font-size:0.9em; ">

            <!-- immediate="true" ? -->

            <!--change to font awesome icons: fa fa-home -->
            <p:menuitem value="Home"       
                        url="/home.xhtml"                      
                        icon="ui-icon-home" 
                        title="return to home page"
                        style="color:#{menuBean.homePage?'#ff5300':''}; font-weight:#{menuBean.homePage?'bold':'normal'}"/>

            <p:menuitem value="Structure Search"  
                        disabled="#{menuBean.currentUser.guest}"
                        icon="ui-icon-search" 
                        url="/structure_search.xhtml"    
                        title="enter criteria to search Structures"
                        style="color:#{menuBean.structureSearchPage?'#ff5300':''}; font-weight:#{menuBean.structureSearchPage?'bold':'normal'}"/>

            <p:menuitem value="My Searches"  
                        disabled="#{menuBean.currentUser.guest}"
                        icon="ui-icon-circle-zoomout" 
                        url="/searches.xhtml"    
                        title="view your saved Searches"
                        style="color:#{menuBean.searchesPage?'#ff5300':''}; font-weight:#{menuBean.searchesPage?'bold':'normal'}"/>

            <p:menuitem value="My Labels"  
                        disabled="#{menuBean.currentUser.guest}"
                        icon="ui-icon-tag" 
                        url="/labels.xhtml"    
                        title="view and manage your Structure Labels"
                        style="color:#{menuBean.labelsPage?'#ff5300':''}; font-weight:#{menuBean.labelsPage?'bold':'normal'}"/>

            <p:menuitem value="Script Manager"  
                        disabled="#{sessionBean.user.name ne 'Russell Williams'}" 
                        icon="ui-icon-script" 
                        url="/script_mgr.xhtml"    
                        title="view and manage your Analysis/Calculation Scripts"
                        style="color:#{menuBean.scriptMgrPage?'#ff5300':''}; font-weight:#{menuBean.scriptMgrPage?'bold':'normal'}"/>

            <p:menuitem value="New Structure"  
                        disabled="#{menuBean.currentUser.guest or !menuBean.currentUser.isRoleContributor}"
                        icon="ui-icon-plus" 
                        action="#{menuBean.gotoNewStructurePage}"
                        title="upload a new Structure file"
                        style="color:#{menuBean.newStructurePage?'#ff5300':''}; font-weight:#{menuBean.newStructurePage?'bold':'normal'}"/>

            <p:menuitem value="About"  
                        icon="ui-icon-info" 
                        url="/about.xhtml"   
                        style="color:#{menuBean.aboutPage?'#ff5300':''}; font-weight:#{menuBean.aboutPage?'bold':'normal'};"/>



            <p:submenu label="Admin" rendered="#{menuBean.currentUser.isRoleAdmin}" >

                <p:menuitem value="Schedule"  
                            icon="ui-icon ui-icon-clock" 
                            styleClass="#{menuBean.autoProcessIsStarted ? 'greenMenuIcon' : ''}"
                            url="/schedule.xhtml"    
                            title="manage the automated schedule "
                            style="color:#{menuBean.schedulePage?'#ff5300':''}; font-weight:#{menuBean.schedulePage?'bold':'normal'}"/>

                <p:menuitem value="Admin Actions"  
                            icon="ui-icon-wrench" 
                            url="/admin_actions.xhtml"    
                            title="perform various adminstrative actions"
                            style="color:#{menuBean.adminActionPage?'#ff5300':''}; font-weight:#{menuBean.adminActionPage?'bold':'normal'}"/>
                
                <p:menuitem value="Amino Acids"  
                            icon="ui-icon-bullet" 
                            url="/amino_acids.xhtml"    
                            title="manage Amino Acid list"
                            style="color:#{menuBean.aminoAcidPage?'#ff5300':''}; font-weight:#{menuBean.aminoAcidPage?'bold':'normal'}"/>
                

                <p:menuitem value="Lookups"  
                            icon="ui-icon-grip-solid-horizontal" 
                            url="/lookups.xhtml"    
                            title="manage lookup lists"
                            style="color:#{menuBean.lookupsPage?'#ff5300':''}; font-weight:#{menuBean.lookupsPage?'bold':'normal'}"/>

                <p:menuitem value="Users/Roles"  
                            icon="ui-icon-key" 
                            url="/roles.xhtml"    
                            title="add/delete #{props.get.appName} roles "
                            style="color:#{menuBean.rolesPage?'#ff5300':''}; font-weight:#{menuBean.rolesPage?'bold':'normal'}"/>

            </p:submenu>




            <p:submenu label="Developer" rendered="#{menuBean.currentUser.isRoleDeveloper}" >

                <p:menuitem value="Properties"         
                            url="/properties.xhtml"        
                            icon="ui-icon-gear"    
                            title="manage/view dynamic and static #{propUtil.appName} properties" 
                            style="color:#{menuBean.propertiesPage?'#ff5300':''}; font-weight:#{menuBean.propertiesPage?'bold':'normal'}"/>

                <p:menuitem value="Tomcat"         
                            url="#{menuBean.tomcatUrl}"        
                            icon="ui-icon-newwin"    
                            target="_BLANK"
                            title="open Tomcat Web Application Manager (username/password required)" />

                <!--<p:separator /> -->

                <p:menuitem value="refresh session"
                            action="#{menuBean.refreshSession}"  
                            icon="ui-icon-refresh"
                            title="refresh all session settings, and return to home page"> 
                </p:menuitem>

            </p:submenu>



        </p:menu>


        <!-- primefaces_users_guide_3_4.pdf, pg 277
        Icons: There are two ways to specify an icon of a menuitem, you can either use bundled icons within PrimeFaces or provide your own via css.
        
        ThemeRoller Icons
          <p:menuitem icon="ui-icon-disk" ... />
        
        Custom Icons
          <p:menuitem icon="barca" ... />
          
          .barca { background: url(barca_logo.png) no-repeat;
                   height:16px;
                   width:16px; }
        -->



        <!-- database, version, instance  -->

        <p:tooltip for="version" >
            <h:outputText value="#{msg.AppFullInstance}"/><br/>          
            <h:outputText value="Database: #{msg.AppDatabase}"/><br/>       
        </p:tooltip>


        <h:panelGroup id="version" styleClass="version" layout="block">

            <h:outputText value="#{msg.AppInstance}" style="font-weight:bold"/>
            <br/>
            <h:outputText value="version #{msg.AppVersion} &bull; #{msg.AppDate}"/>

        </h:panelGroup>


        <!--
        <div class="betaMode" style="width:95%; text-align: center">
            <h:outputText value="#{msg.AppVersion} beta" />
        </div>
        -->



    </h:form>






</ui:composition>