src/main/java/com/just/jstruct/model/Jstruct_AminoAcid.java
package com.just.jstruct.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Entity class for: amino_acid_def
 */
// -------------------------------------------------------------------------------------
// Copyright (c) 2023 Just-Evotec Biologics, Inc.
// All rights reserved
// See the LICENSE.txt file included with this library for license terms and conditions.
// -------------------------------------------------------------------------------------
@Entity
@Table(name = "amino_acid_def", schema = "public")
@NamedQueries({
    @NamedQuery(name = "Jstruct_AminoAcid.findAll", 
                                                        query = "SELECT aa FROM Jstruct_AminoAcid aa"),
    
    @NamedQuery(name = "Jstruct_AminoAcid.findByAminoAcidDefId", 
                                                        query = "SELECT aa FROM Jstruct_AminoAcid aa "
                                                              + "WHERE aa.aminoAcidDefId = :aminoAcidDefId"),
    
    @NamedQuery(name = "Jstruct_AminoAcid.findByName", 
                                                        query = "SELECT aa FROM Jstruct_AminoAcid aa "
                                                              + "WHERE aa.name = :name"),
    
    @NamedQuery(name = "Jstruct_AminoAcid.findByAbbrev", 
                                                        query = "SELECT aa FROM Jstruct_AminoAcid aa "
                                                              + "WHERE aa.abbrev = :abbrev"),
    
    @NamedQuery(name = "Jstruct_AminoAcid.findByOneLetter", 
                                                        query = "SELECT aa FROM Jstruct_AminoAcid aa "
                                                              + "WHERE aa.oneLetter = :oneLetter"),
    
    @NamedQuery(name = "Jstruct_AminoAcid.findAllByAminoAcidIds", 
                                                        query = "SELECT aa FROM Jstruct_AminoAcid aa "
                                                              + "WHERE aa.aminoAcidDefId in (:aminoAcidIds)")
})
public class Jstruct_AminoAcid implements Serializable {

    
    private static final long serialVersionUID = 1L;
    @Id
    
    //@GeneratedValue(strategy = GenerationType.IDENTITY)
    @SequenceGenerator(name="amino_acid_def_amino_acid_def_id_seq", sequenceName="amino_acid_def_amino_acid_def_id_seq", allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="amino_acid_def_amino_acid_def_id_seq")
    
    @Basic(optional = false)
    @Column(name = "amino_acid_def_id", updatable=false)
    private Long aminoAcidDefId;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "name")
    private String name;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 3)
    @Column(name = "abbrev")
    private String abbrev;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "one_letter")
    private Character oneLetter;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "is_standard")
    private Character isStandard;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "atoms")
    private String atoms;
    
    /* ------------ audit fields ------------ */
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "insert_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date insertDate;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "update_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date updateDate;
    
    @Column(name = "insert_user_id", insertable=false, updatable=false)
    private Long insertUserId;
    
    @Basic(optional = false)
    @NotNull
    @JoinColumn(name = "insert_user_id", referencedColumnName = "user_id")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Jstruct_User insertUser;
    
    @Column(name = "update_user_id", insertable=false, updatable=false)
    private Long updateUserId;
    
    @Basic(optional = false)
    @NotNull
    @JoinColumn(name = "update_user_id", referencedColumnName = "user_id")
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    private Jstruct_User updateUser;
    
    /* --------- end audit fields --------- */
    
    
    
    

    public Jstruct_AminoAcid() {
        isStandard = 'N';
    }

    


    
    
    

    public Long getAminoAcidDefId() {
        return aminoAcidDefId;
    }

    public void setAminoAcidDefId(Long aminoAcidDefId) {
        this.aminoAcidDefId = aminoAcidDefId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAbbrev() {
        return abbrev;
    }

    public void setAbbrev(String abbrev) {
        this.abbrev = abbrev;
    }

    public Character getOneLetter() {
        return oneLetter;
    }

    public void setOneLetter(Character oneLetter) {
        this.oneLetter = oneLetter;
    }

    public boolean isStandard() { return isStandard.equals('Y') || isStandard.equals('y'); }
    public void setStandard(boolean isStandard) { this.isStandard = isStandard ? 'Y' : 'N' ; }
    

    public String getAtoms() {
        return atoms;
    }

    public void setAtoms(String atoms) {
        this.atoms = atoms;
    }

    
    public Date getInsertDate() {return insertDate;}
    public void setInsertDate(Date insertDate) {this.insertDate = insertDate; }

    public Date getUpdateDate() {return updateDate;}
    public void setUpdateDate(Date updateDate) { this.updateDate = updateDate;}

    public long getInsertUserId() {return insertUserId;}
    public void setInsertUserId(long insertUserId) { this.insertUserId = insertUserId;}
    
    public Jstruct_User getInsertUser() {return insertUser;}
    public void setInsertUser(Jstruct_User insertUser) { this.insertUser = insertUser;}

    public long getUpdateUserId() { return updateUserId;}
    public void setUpdateUserId(long updateUserId) {this.updateUserId = updateUserId;}
    
    public Jstruct_User getUpdateUser() {return updateUser;}
    public void setUpdateUser(Jstruct_User updateUser) { this.updateUser = updateUser;}

    
    
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (aminoAcidDefId != null ? aminoAcidDefId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Jstruct_AminoAcid)) {
            return false;
        }
        Jstruct_AminoAcid other = (Jstruct_AminoAcid) object;
        if ((this.aminoAcidDefId == null && other.aminoAcidDefId != null) || (this.aminoAcidDefId != null && !this.aminoAcidDefId.equals(other.aminoAcidDefId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.just.jstruct.model.Jstruct_AminoAcid[ aminoAcidDefId=" + aminoAcidDefId + " ]";
    }
    
}

src/main/java/com/just/jstruct/model/Jstruct_AnalysisFile.java
package com.just.jstruct.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Entity class for: analysis_file
 */
// -------------------------------------------------------------------------------------
// Copyright (c) 2017 Just Biotherapeutics, Inc.
// All rights reserved
// See the LICENSE.txt file included with this library for license terms and conditions.
// -------------------------------------------------------------------------------------
@Entity
@Table(name = "analysis_file", schema = "public")
@NamedQueries({
    @NamedQuery(name = "Jstruct_AnalysisFile.findById", 
                                                query = "SELECT af FROM Jstruct_AnalysisFile af "
                                                      + " WHERE af.analysisFileId = :analysisFileId"),
    
    @NamedQuery(name = "Jstruct_AnalysisFile.findByAnalysisScriptVerId", 
                                                query = "SELECT af FROM Jstruct_AnalysisFile af "
                                                      + " WHERE af.analysisScriptVerId = :analysisScriptVerId")
})
public class Jstruct_AnalysisFile implements Serializable 
{

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="analysis_file_analysis_file_id_seq", sequenceName="analysis_file_analysis_file_id_seq", allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="analysis_file_analysis_file_id_seq")
    @Basic(optional = false)
    @Column(name = "analysis_file_id")
    private Long analysisFileId;
   
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "file_name")
    private String fileName;
    
    @Column(name = "file_data")
    private byte[] fileData;
    
    //fk to analysis_script_ver
    @Basic(optional = false)
    @NotNull
    @Column(name = "analysis_script_ver_id")
    private Long analysisScriptVerId;
    
    
    
    
    public Jstruct_AnalysisFile() {
    }

    public Jstruct_AnalysisFile(String fileName, byte[] fileData) 
    {
        this.fileName = fileName;
        this.fileData = fileData;
    }
    
    
    

    public Long getAnalysisFileId() {  return analysisFileId;  }
    public void setAnalysisFileId(Long analysisFileId) { this.analysisFileId = analysisFileId; }

    public String getFileName() { return fileName; }
    public void setFileName(String fileName) {  this.fileName = fileName; }

    public byte[] getFileData() {  return fileData; }
    public void setFileData(byte[] fileData) { this.fileData = fileData; }

    public Long getAnalysisScriptVerId() { return analysisScriptVerId; }
    public void setAnalysisScriptVerId(Long analysisScriptVerId) { this.analysisScriptVerId = analysisScriptVerId; }
    
    
    
    
    
    
    
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (analysisFileId != null ? analysisFileId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Jstruct_AnalysisFile)) {
            return false;
        }
        Jstruct_AnalysisFile other = (Jstruct_AnalysisFile) object;
        if ((this.analysisFileId == null && other.analysisFileId != null) || (this.analysisFileId != null && !this.analysisFileId.equals(other.analysisFileId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.just.jstruct.model.Jstruct_AnalysisFile[ analysisFileId=" + analysisFileId + " ]";
    }
    
}

src/main/java/com/just/jstruct/model/Jstruct_AnalysisTask.java
package com.just.jstruct.model;

import com.hfg.util.StringUtil;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Entity class for: analysis_task
 */
// -------------------------------------------------------------------------------------
// Copyright (c) 2017 Just Biotherapeutics, Inc.
// All rights reserved
// See the LICENSE.txt file included with this library for license terms and conditions.
// -------------------------------------------------------------------------------------
@Entity
@Table(name = "analysis_task", schema = "public")
@NamedQueries({
     @NamedQuery(name = "Jstruct_AnalysisTask.findById", 
                                                query = "SELECT a FROM Jstruct_AnalysisTask a "
                                                     + " WHERE a.analysisTaskId = :analysisTaskId"),
    
    @NamedQuery(name = "Jstruct_AnalysisTask.findByStatus", 
                                                query = "SELECT a FROM Jstruct_AnalysisTask a "
                                                      + " WHERE a.status = :status"),
    
    @NamedQuery(name = "Jstruct_AnalysisTask.findByAnalysisRunId", 
                                                query = "SELECT a FROM Jstruct_AnalysisTask a "
                                                      + " WHERE a.analysisRunId = :analysisRunId")
})
public class Jstruct_AnalysisTask implements Serializable 
{

    private static final long serialVersionUID = 1L;
    
    @Id
    @SequenceGenerator(name="analysis_task_analysis_task_id_seq", sequenceName="analysis_task_analysis_task_id_seq", allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator="analysis_task_analysis_task_id_seq")
    @Basic(optional = false)
    @Column(name = "analysis_task_id")
    private Long analysisTaskId;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 2000)
    @Column(name = "command")
    private String command;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "status")
    private String status;
    
    @Size(max = 2147483647)
    @Column(name = "error")
    private String error;
    
    @Basic(optional = false)
    @NotNull
    @Column(name = "start_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date startDate;
    
    @Column(name = "end_date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date endDate;

    
    //fk to struct_version
    @Basic(optional = false)
    @NotNull
    @Column(name = "struct_ver_id")
    private Long structVerId;
    
    //fk to analysis_run
    @Basic(optional = false)
    @NotNull
    @Column(name = "analysis_run_id")
    private Long analysisRunId;
    
    
    
    
    
    
    public Jstruct_AnalysisTask() {
    }

    
    
    
    

    public Long getAnalysisTaskId() {  return analysisTaskId; }
    public void setAnalysisTaskId(Long analysisTaskId) { this.analysisTaskId = analysisTaskId; }

    public String getCommand() { return command; }
    public void setCommand(String command) { this.command = StringUtil.isSet(command) ? command.trim() : null; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getError() { return error; }
    public void setError(String error) { this.error = error; }

    public Date getStartDate() { return startDate; }
    public void setStartDate(Date startDate) { this.startDate = startDate; }

    public Date getEndDate() { return endDate; }
    public void setEndDate(Date endDate) { this.endDate = endDate; }
    
    
    public Long getStructVerId() { return structVerId; }
    public void setStructVerId(Long structVerId) { this.structVerId = structVerId; }

    public Long getAnalysisRunId() { return analysisRunId; }
    public void setAnalysisRunId(Long analysisRunId) {  this.analysisRunId = analysisRunId; }
    
    
    
    
    
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (analysisTaskId != null ? analysisTaskId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Jstruct_AnalysisTask)) {
            return false;
        }
        Jstruct_AnalysisTask other = (Jstruct_AnalysisTask) object;
        if ((this.analysisTaskId == null && other.analysisTaskId != null) || (this.analysisTaskId != null && !this.analysisTaskId.equals(other.analysisTaskId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.just.jstruct.model.AnalysisTask[ analysisTaskId=" + analysisTaskId + " ]";
    }
    
}

src/main/webapp/amino_acids.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:p="http://primefaces.org/ui"
                template="/layout/template.xhtml">

    <ui:define name="title"> <h:outputText value="Amino Acids"/> </ui:define>


    <ui:define name="content" >


        <p:tabView id="tabAminoAcids">


            <p:tab id="tab_aa" title="Amino Acid" >

                <p:dataTable id="aminoAcidTable" value="#{aminoAcidList.aminoAcids}" var="aa"  sortMode="multiple" resizableColumns="true" style="padding:20px">

                    <f:facet name="header">  
                        <h:outputText value="Amino Acid list"/>
                    </f:facet> 

                    <p:column headerText="Name" sortBy="#{aa.name}" width="20%">
                        <h:outputText value="#{aa.name}" />
                    </p:column>

                    <p:column headerText="3 Letter Code" sortBy="#{aa.threeLetterCode}" width="10%">
                        <h:outputText value="#{aa.threeLetterCode} "  style="font-weight: bold; "/>
                        <h:outputText value=" (#{aa.aminoAcid.threeLetterCode})" style="color: #bbbbbb" rendered="#{aa.aminoAcid.threeLetterCode ne aa.threeLetterCode}"/> 
                    </p:column>

                    <p:column headerText="1 Letter Code" sortBy="#{aa.aminoAcid.oneLetterCode}" width="10%" >
                        <h:outputText value="#{aa.aminoAcid.oneLetterCode}" />
                    </p:column>

                    <p:column headerText="is Standard" sortBy="#{aa.standard}" width="10%" >
                        <h:outputText value="Y" rendered="#{aa.standard}"/>
                    </p:column>

                    <p:column headerText="Atoms" sortBy="#{aa.atomNames}" width="50%" >
                        <h:outputText value="#{aa.atomNames}"/>
                    </p:column>

                </p:dataTable>

            </p:tab>



            <p:tab id="tab_aa_otherc" title="Other" >
                
                <p:panelGrid columns="3" columnClasses="column33,column33,column33" >

                    
                    <p:dataTable id="nucleicAcids" value="#{aminoAcidList.nucleicAcidMap.entrySet().toArray()}" var="na" resizableColumns="true" style="padding-right:10px">
                        <f:facet name="header">  
                            <h:outputText value="Nucleic Acid"/>
                        </f:facet> 
                        
                        <p:column headerText="Key"  width="50%" >
                            <h:outputText value="#{na.key}"/>
                        </p:column>
                        
                        <p:column headerText="Abbrev" width="50%" >
                            <h:outputText value="#{na.value}"/>
                        </p:column>
                        
                    </p:dataTable>
                    
                    
                    
                    
                    <p:dataTable id="backboneAtoms" value="#{aminoAcidList.bkbnAtoms}" var="a"  sortMode="multiple" resizableColumns="true" style="padding-right:10px">
                        <f:facet name="header">  
                            <h:outputText value="Backbone Atoms"/>
                        </f:facet> 
                        
                        <p:column headerText="Atom" sortBy="#{a.name}" width="33%" >
                            <h:outputText value="#{a.name}"/>
                        </p:column>
                        
                        <p:column headerText="Element" sortBy="#{a.element.symbol}" width="33%" >
                            <h:outputText value="#{a.element.symbol}"/>
                        </p:column>
                        
                    </p:dataTable>
                    
                    
                    
                    <p:dataTable id="backboneCbAtoms" value="#{aminoAcidList.bkbnCbAtoms}" var="a"  sortMode="multiple" resizableColumns="true" style="padding-right:10px">
                        <f:facet name="header">  
                            <h:outputText value="Backbone CB Atoms"/>
                        </f:facet> 
                        
                        <p:column headerText="Atom" sortBy="#{a.name}" width="33%" >
                            <h:outputText value="#{a.name}"/>
                        </p:column>
                        
                        <p:column headerText="Element" sortBy="#{a.element.symbol}" width="33%" >
                            <h:outputText value="#{a.element.symbol}"/>
                        </p:column>
                        
                    </p:dataTable>
                    
                    

                </p:panelGrid>
            </p:tab>

        </p:tabView>







        <!-- new amino acid - form 

        <div style="padding:10px 10px 10px 10px">
            <p:panel header="New Amino Acid" toggleable="true" >

                <h:form id="aminoAcidNewForm">

                    <h:panelGrid columns="2" id="aminoAcidPanelGrid" styleClass="standard" columnClasses="lblL,data" >

                        <h:outputLabel value="Name" />
                        <h:panelGroup style="display:block; overflow:hidden; box-sizing:border-box;">
                            <p:inputText id="aminoAcidName"
                                         style="box-sizing:border-box; width:100%;"
                                         styleClass="rqd"
                                         size="100" 
                                         maxlength="255"
                                         value="#{aminoAcidList.newAminoAcid.name}"
                                         required="true"
                                         requiredMessage="Name cannot be blank">
                            </p:inputText>
                            <br/>
                            <p:message for="aminoAcidName" id="nameMsg" />
                        </h:panelGroup>


                        <h:outputLabel value="Abbrev (3)" />
                        <h:panelGroup>
                            <p:inputText id="aminoAcidAbbrev3"
                                         styleClass="rqd"
                                         size="20" 
                                         maxlength="3"
                                         value="#{aminoAcidList.newAminoAcid.abbrev}"
                                         required="true"
                                         requiredMessage="Abbrev (3) cannot be blank">
                            </p:inputText>
                            <br/>
                            <p:message for="aminoAcidAbbrev3" id="abbrev3Msg" />
                        </h:panelGroup>


                        <h:outputLabel value="Abbrev (1)" />
                        <h:panelGroup>
                            <p:inputText id="aminoAcidAbbrev1"
                                         styleClass="rqd"
                                         size="10" 
                                         maxlength="1"
                                         value="#{aminoAcidList.newAminoAcid.oneLetter}"
                                         required="true"
                                         requiredMessage="Abbrev (1) cannot be blank">
                            </p:inputText>
                            <br/>
                            <p:message for="aminoAcidAbbrev1" id="abbrev1Msg" />
                        </h:panelGroup>



                        <h:outputLabel value="Standard" />
                        <p:selectBooleanCheckbox value="#{aminoAcidList.newAminoAcid.standard}" />



                        <h:outputLabel value="Atoms" />
                        <h:panelGroup style="display:block; overflow:hidden; box-sizing:border-box;">
                            <p:inputText id="aminoAcidAtoms"
                                         style="box-sizing:border-box; width:100%;"
                                         styleClass="rqd"
                                         size="10" 
                                         maxlength="1"
                                         value="#{aminoAcidList.newAminoAcid.atoms}"
                                         required="true"
                                         requiredMessage="Atoms cannot be blank">
                            </p:inputText>
                            <br/>
                            <p:message for="aminoAcidAtoms" id="atomsMsg" />
                        </h:panelGroup>



                        <f:facet name="footer">
                            <p:commandButton action="#{aminoAcidList.save}"
                                             value="Add"
                                             icon="ui-icon-plus"
                                             style="margin:8px 20px 8px 20px"
                                             update="aminoAcidPanelGrid"/>
                        </f:facet>

                    </h:panelGrid>

                </h:form>
            </p:panel>
        </div>

        -->

        <!-- amino acid list - form 

        <h:form id="aminoAcidListForm" style="padding:10px 10px 50px 10px">

            <p:growl id="msgs" showDetail="true"/>

            <p:dataTable id="aminoAcidTable" value="#{aminoAcidList.aminoAcids}" var="aa" 
                         editable="true" sortMode="multiple" resizableColumns="true">

                <f:facet name="header">  
                    <h:outputText value="Amino Acid list"/>
                </f:facet> 

                <p:column style="width:32px">
                    <p:rowEditor />
                </p:column>

                <p:ajax event="rowEdit" listener="#{aminoAcidList.onRowEdit}" update=":aminoAcidListForm:msgs" />
                <p:ajax event="rowEditCancel" listener="#{aminoAcidList.onRowCancel}" update=":aminoAcidListForm:msgs" />

                <p:column headerText="Name" sortBy="#{aa.name}" width="30%" filterBy="#{aa.name}" filterMatchMode="contains">
                    <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{aa.name}" /></f:facet>
                        <f:facet name="input"><p:inputText value="#{aa.name}" style="width:100%" label="Name"/></f:facet>
                    </p:cellEditor>
                </p:column>


                <p:column headerText="Abbrev (3)" sortBy="#{aa.abbrev}" width="10%" style="font-weight:bold;" filterBy="#{aa.abbrev}" filterMatchMode="contains">
                    <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{aa.abbrev}" /></f:facet>
                        <f:facet name="input"><p:inputText value="#{aa.abbrev}" style="width:100%" label="Abbrev (3)"/></f:facet>
                    </p:cellEditor>
                </p:column>


                <p:column headerText="Abbrev (1)" sortBy="#{aa.oneLetter}" width="10%" filterBy="#{aa.oneLetter}" filterMatchMode="exact">
                    <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{aa.oneLetter}" /></f:facet>
                        <f:facet name="input"><p:inputText value="#{aa.oneLetter}" style="width:100%" label="Abbrev (1)"/></f:facet>
                    </p:cellEditor>
                </p:column>


                <p:column headerText="Standard" sortBy="#{aa.standard}" width="10%">
                    <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{aa.standard?'Yes':''}" /></f:facet>
                        <f:facet name="input">
                            <p:selectBooleanCheckbox value="#{aa.standard}" />
                        </f:facet>
                    </p:cellEditor>
                </p:column>


                <p:column headerText="Atoms" width="50%" filterBy="#{aa.atoms}" filterMatchMode="contains">
                    <p:cellEditor>
                        <f:facet name="output"><h:outputText value="#{aa.atoms}" /></f:facet>
                        <f:facet name="input"><p:inputText value="#{aa.atoms}" style="width:100%" label="Atoms"/></f:facet>
                    </p:cellEditor>
                </p:column>



            </p:dataTable>

        </h:form>

        -->






    </ui:define>

</ui:composition>